[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables devono essere configurate nel dashboard Netlify
# Non includere credenziali sensibili in questo file

