[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://ssjzkdunniggfcsodvtx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzanprZHVubmlnZ2Zjc29kdnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzQzMTgsImV4cCI6MjA3MTgxMDMxOH0.wun-KeKry3PJ9ujTrJzidXMFhT80ZwEbkyDz9FoAg_0"
  VITE_FIREBASE_API_KEY = "AIzaSyD97Bgyg0SwVPF9rZS4BCSWKP20LxXfaqM"
  VITE_FIREBASE_AUTH_DOMAIN = "dallelec-gestion-58a49.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "dallelec-gestion-58a49"
  VITE_FIREBASE_STORAGE_BUCKET = "dallelec-gestion-58a49.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "801397923579"
  VITE_FIREBASE_APP_ID = "1:801397923579:web:b07860aadfeef5c1579a5e"
  VITE_FIREBASE_MEASUREMENT_ID = "G-G3CLCT2ERB"

